[build]
  command = "npx prisma generate && next build --no-lint"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# タイムアウト設定を環境変数で指定
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  AWS_LAMBDA_FUNCTION_TIMEOUT = "26"
  NODE_OPTIONS = "--max-old-space-size=4096"